config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_kitty:
    dst: ~/.config/kitty
    src: config/kitty
  f_starship.toml:
    dst: ~/.config/starship.toml
    src: config/starship.toml
profiles:
  general:
    dotfiles:
    - f_starship.toml
    - d_kitty
