config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_kitty:
    dst: ~/.config/kitty
    src: config/kitty
  f_starship.toml:
    dst: ~/.config/starship.toml
    src: config/starship.toml
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_fonts:
    src: fonts
    dst: ~/.fonts
profiles:
  general:
    dotfiles:
    - f_starship.toml
    - d_kitty
    - d_gtk-3.0
    - d_fonts
  bspwm:
    dotfiles:
    - d_bspwm
    - d_sxhkd
