config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_kitty:
    dst: ~/.config/kitty
    src: config/kitty
  f_starship.toml:
    dst: ~/.config/starship.toml
    src: config/starship.toml
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
profiles:
  general:
    dotfiles:
    - f_starship.toml
    - d_kitty
  bspwm:
    dotfiles:
    - d_bspwm
    - d_sxhkd
